version: '3.7'

services:
  rutynka-web:
      volumes:
        - ./_devops/config/ssl_cert/prd:/ssl
      restart: always
      ports:
          - "443:443"
          - "80:80"
  erdos-node:
    build:
      context: ./_devops/dockerfiles/node
      target: production
    env_file: ./_devops/node/.env.prd
  erdos-fiber:
      target: production