version: '3.9'

services:
  erdos-proxy:
      build: ./_devops/nginx
      image: marcin0/minus-na-plus:proxy
      depends_on:
        erdos-fiber:
          condition: service_started
        erdos-fastify:
          condition: service_started
      volumes:
          - ./_devops/config/local.conf:/etc/nginx/conf.d/site.conf
          - ./nginx-log:/var/log/nginx
          - ./_devops/config/ssl_cert/prd:/ssl
          - ./front_app:/var/www/vhosts/front_app/
          - apps-data:/var/www
      links:
          - erdos-fiber
          - erdos-fastify
      container_name: erdos-proxy
      ports:
        - "80:80"
      restart: always
  erdos-fastify:
      image: marcin0/minus-na-plus:fastify
      build:
        context: _devops/fastify
        target: dev
      env_file: _devops/fastify/.env
      volumes:
        - ./fastify_api:/home/node/src/app
        - apps-data:/home
      container_name: erdos-fastify
      restart: always
  erdos-fiber:
      image: marcin0/minus-na-plus:fiber
      build:
        context: ./_devops/fiber
        target: dev
      volumes:
        - ./fiber_api:/usr/src
        - apps-data:/usr
      container_name: erdos-fiber
      restart: always
volumes:
  apps-data:
    driver: local

