version: '3.9'

services:
  erdos-proxy:
      build: ./_devops/nginx
      image: marcin0/minus-na-plus:proxy
      depends_on:
        erdos-fiber:
          condition: service_started
      volumes:
          - ./_devops/config/local.conf:/etc/nginx/conf.d/site.conf
          - ./nginx-log:/var/log/nginx
          - ./_devops/config/ssl_cert/local:/ssl
          - ./front_app:/var/www/vhosts/front_app/
      links:
          - erdos-fiber
          - erdos-node
      container_name: erdos-proxy
      ports:
        - "80:80"
      restart: always
  erdos-node:
      image: marcin0/minus-na-plus:node
      build:
        context: ./_devops/node
        target: dev
      env_file: ./_devops/node/.env
      volumes:
        - ./fastify_api:/home/node/src/app
      container_name: erdos-node
      restart: always
  erdos-fiber:
      image: marcin0/minus-na-plus:fiber
      build:
        context: ./_devops/fiber
        target: dev
      volumes:
        - ./fiber_api:/usr/src
      container_name: erdos-fiber
      restart: always

