version: '3.9'

services:
  erdos-proxy:
      build: ./_devops/nginx
      image: marcin0/minus-na-plus:proxy0.1
      volumes:
        - apps-data:/var/www
        - apps-data:/var/etc
        - ./_devops/config/ssl_cert/prd:/ssl
      restart: always
      ports:
          - "443:443"
          - "80:80"
  erdos-fastify:
    image: marcin0/minus-na-plus:fastify0.1
    volumes:
      - apps-data:/home
    build:
      context: ./_devops/fastify
      target: production
    env_file: _devops/fastify/.env.prd
    environment:
      APP_ENV: prod
  erdos-fiber:
    image: marcin0/minus-na-plus:fiber0.1
    build:
      context: ./_devops/fiber
      target: production
    environment:
      APP_ENV: prod
volumes:
  apps-data:
    driver: local