name: golangci-lint

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./fiber_api/erdos
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: golangci-lint
#        uses: golangci/golangci-lint-action@v3
        uses: reviewdog/action-golangci-lint@v2
        with:
          version: latest