name: mathlogic-test
on:
  push:
    branch:
      - master
jobs:
  job-first:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./fiber_api/erdos
    steps:
      - uses: actions/cache@v3
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19.x
      - name: Install dependencies
        run: go mod download
#      - name: Build
#        run: go build -v ./...
#        env:
#          GOPATH: ./fiber_api
      - name: mathlogict test
        run: go test -v ./mathlogic/.

