name: "Security Scan"

# Run workflow each time code is pushed to your repository and on a schedule.
# The scheduled workflow runs every at 00:00 on Sunday UTC time.
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  sec-scan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./fiber_api/erdos
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19.x
      - name: Install dependencies
        run: go mod download
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
            # NOTE add -no-fail to skip
          args: -color ./...